# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PricePower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PricePower

  target 'PricePowerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PricePowerUITests' do
    inherit! :search_paths
    # Pods for testing
  end
	
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON'

end
